// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Ver meu perfil",
  description: "Retorna o perfil do usu\xE1rio autenticado (nome, unidade, cargo, papel).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = db(ctx);
    const uid = ctx.getUserId();
    const [profile, roles] = await Promise.all([
      supabase.from("profiles").select("*").eq("id", uid).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", uid)
    ]);
    if (profile.error) {
      return { content: [{ type: "text", text: profile.error.message }], isError: true };
    }
    const payload = { ...profile.data, roles: (roles.data ?? []).map((r) => r.role) };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-announcements.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_announcements_default = defineTool2({
  name: "list_announcements",
  title: "Listar avisos",
  description: "Lista os avisos/comunicados mais recentes do painel da equipe.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de avisos (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await db2(ctx).from("announcements").select("id, message, type, unit, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { announcements: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-ideas.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_ideas_default = defineTool3({
  name: "list_my_ideas",
  title: "Minhas ideias",
  description: "Lista as sugest\xF5es que o usu\xE1rio autenticado enviou para a Caixa de Ideias.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = db3(ctx);
    const { data, error } = await supabase.from("ideas").select("id, title, description, category, status, created_at").eq("author_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const { data: replyRows } = await supabase.rpc("get_idea_replies");
    const replyMap = {};
    (replyRows ?? []).forEach((r) => replyMap[r.idea_id] = r.manager_reply);
    const ideas = (data ?? []).map((i) => ({ ...i, manager_reply: replyMap[i.id] ?? null }));
    return {
      content: [{ type: "text", text: JSON.stringify(ideas, null, 2) }],
      structuredContent: { ideas }
    };
  }
});

// src/lib/mcp/tools/submit-idea.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var submit_idea_default = defineTool4({
  name: "submit_idea",
  title: "Enviar ideia",
  description: "Envia uma nova sugest\xE3o para a Caixa de Ideias em nome do usu\xE1rio autenticado.",
  inputSchema: {
    title: z2.string().trim().min(3).max(120).describe("T\xEDtulo curto da ideia."),
    description: z2.string().trim().min(5).max(2e3).describe("Descri\xE7\xE3o detalhada."),
    category: z2.string().trim().max(60).optional().describe("Categoria opcional (ex: atendimento, produtos).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await db4(ctx).from("ideas").insert({
      author_id: ctx.getUserId(),
      title,
      description,
      category: category ?? "geral"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Ideia registrada (id: ${data.id}).` }],
      structuredContent: { idea: data }
    };
  }
});

// src/lib/mcp/tools/log-pulse.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_pulse_default = defineTool5({
  name: "log_pulse",
  title: "Registrar humor do dia",
  description: "Registra ou atualiza o pulso (humor) do usu\xE1rio para o dia de hoje.",
  inputSchema: {
    mood: z3.enum(["otimo", "bom", "ok", "cansado", "ruim"]).describe("Humor de hoje.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ mood }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = db5(ctx);
    const uid = ctx.getUserId();
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const existing = await supabase.from("pulses").select("id").eq("user_id", uid).eq("day", today).maybeSingle();
    const op = existing.data ? await supabase.from("pulses").update({ mood }).eq("id", existing.data.id).select().single() : await supabase.from("pulses").insert({ user_id: uid, day: today, mood }).select().single();
    if (op.error) return { content: [{ type: "text", text: op.error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Pulso do dia salvo: ${mood}` }],
      structuredContent: { pulse: op.data }
    };
  }
});

// src/lib/mcp/tools/my-performance.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function db6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_performance_default = defineTool6({
  name: "my_performance",
  title: "Meu desempenho",
  description: "Retorna os snapshots de desempenho (servi\xE7os, comandas, faturamento) do usu\xE1rio autenticado, filtrando pelo nome do perfil.",
  inputSchema: {
    limit: z4.number().int().min(1).max(24).optional().describe("M\xE1ximo de per\xEDodos (padr\xE3o 6).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = db6(ctx);
    const uid = ctx.getUserId();
    const profile = await supabase.from("profiles").select("nome").eq("id", uid).maybeSingle();
    if (profile.error) return { content: [{ type: "text", text: profile.error.message }], isError: true };
    const nome = profile.data?.nome ?? "";
    const normalize = (s) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
    const snaps = await supabase.from("performance_snapshots").select("period_label, professional_name, services_count, comandas_count, revenue_cents, top_service, created_at").order("created_at", { ascending: false }).limit(200);
    if (snaps.error) return { content: [{ type: "text", text: snaps.error.message }], isError: true };
    const mine = (snaps.data ?? []).filter((r) => normalize(r.professional_name) === normalize(nome)).slice(0, limit ?? 6);
    return {
      content: [{ type: "text", text: JSON.stringify({ nome, snapshots: mine }, null, 2) }],
      structuredContent: { nome, snapshots: mine }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ozwpqeqcigajljkphmex";
var mcp_default = defineMcp({
  name: "sir-alfred-equipe-mcp",
  title: "Sir Alfred Equipe",
  version: "0.1.0",
  instructions: "Ferramentas para a equipe da barbearia Sir Alfred: perfil do usu\xE1rio, avisos, Caixa de Ideias, pulso do dia e hist\xF3rico de desempenho. Todas as a\xE7\xF5es respeitam as permiss\xF5es (RLS) do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_announcements_default, list_my_ideas_default, submit_idea_default, log_pulse_default, my_performance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
